services:
  librecloud-web:
    build: .
    ports:
      - "3019:3000"
    env_file: ".env.local"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=production
    restart: unless-stopped